### ISSUE TITLE
Implement a testing framework

### ISSUE THREAD

**Issue by OskarCarl** [vs-ude/fyr#5]
We want to provide an integrated framework for unit testing, similar to what go [offers](https://golang.org/doc/code.html#Testing).
To achieve this, we need to make some changes deep in the compiler.
Work will be done in the [implement-testing](https://github.com/vs-ude/fyr/tree/implement-testing) branch.

- [ ] lift main function detection from backend to typecheck #7 
  - [ ] replace the main function with the `TestMain` function when testing
- [ ] write the runtime for tests (ref [go testing package](https://golang.org/pkg/testing/)) #6 
- [ ] only include the `*_test.fyr` files when the `test` command is given #8 

This list is incomplete and will be expanded when I am able to gain abetter understanding of the issue.
